server: true
permalink: / 
auto: true
server_port: 4000
baseurl: /
asset_bundler:
  compress:
    js: true
    css: true
  base_path: /bundles/
  server_url:
  remove_bundled: false
  dev: false
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"


